version: "3.8"
services:
  telegram-transcription:
    image: eDukanam-telegram-transcriber:latest
    container_name: telegram-transcription
    ports:
      - "8080:8080"
    restart: unless-stopped
